language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
    - develop
    - /^release.*$/
notifications:
  email:
    - robbl@moj.io

before_script:
  - npm install -g bower@1.3.3
  
script:
  - bower install
  - coffee --map --compile src/nodejs
  - cp src/nodejs/*.js lib/
  - coffee --map --compile src/browser
  - cd src/browser
  - ../../node_modules/.bin/browserify -r ./HttpBrowserWrapper.js --standalone HttpBrowserWrapper > ../../dist/browser/HttpBrowserWrapper.js
  - ../../node_modules/.bin/browserify -r ./MojioClient.js --standalone MojioClient > ../../dist/browser/MojioClient.js
  - cd ../../
  - mocha