language: node_js
node_js:
  - "0.8"
  - "0.10"
branches:
  only:
    - master
notifications:
  email:
    - robbl@moj.io
before_script:
  - npm install -g bower
  - bower install
script:
  - mocha