language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
    - develop
    - /^release.*$/
notifications:
  email:
    - robbl@moj.io

before_script:
  - npm install -g bower
  
script:
  - bower install
  - coffee --map --compile src/nodejs
  - cp src/nodejs/*.js lib/
  - coffee --map --compile src/browser
  - cd src/browser
  - ../../node_modules/.bin/browserify -r ./HttpBrowser.js --standalone HttpBrowser > ../../dist/browser/HttpBrowser.js
  - ../../node_modules/.bin/browserify -r ./HttpBrowser.js --standalone HttpBrowser > ../../dist/browser/HttpBrowser.js
  - cd ../../
  - mocha